timezone: Europe/Berlin

locales_default:
  lang: de_DE.UTF-8
  language: de

locales_gen:
  - de_DE.UTF-8

root_ssh_key: false
root_shell: /usr/bin/fish

debian_distribution: trixie
debian_components:
  - main
  - non-free-firmware

debian_mirror: http://deb.debian.org/debian

debian_backports: false
debian_backports_distribution: "{{debian_distribution}}-backports"

debian_security: true
debian_security_mirror: "{{debian_mirror}}-security"
debian_security_distribution: "{{debian_distribution}}-security"

debian_sources: true
debian_backports_sources: "{{debian_sources}}"
debian_security_sources: "{{debian_sources}}"

common_package_intallation: true
machine_package_installation: true
microcode_update: false
firmware_installation: false

increase_maximum_inotify_user_watches: false

resolvconf_enabled: true
