---
- name: Install Podman and DNS dependencies
  ansible.builtin.apt:
    name:
      - podman
      - dnsmasq
      - containernetworking-plugins
      - podman-compose
      - golang-github-containernetworking-plugin-dnsname
      - aardvark-dns
    state: present
    update_cache: yes
    cache_valid_time: 3600