---

- name: move group
  command: "groupmod --new-name {{ item }} {{ users[item].old_name }}"
  loop: "{{ users.keys() | list }}"
  when: users[item].old_name is defined
  failed_when: false

- name: move account
  command: "usermod --login {{ item }} {{ users[item].old_name }}"
  loop: "{{ users.keys() | list }}"
  when: users[item].old_name is defined
  failed_when: false
