---
- import_tasks: cleanup.yaml

- import_tasks: setup_Debian.yaml

- import_tasks: ansible.yaml

- import_tasks: mitogen.yaml
  when: ansible_use_mitogen

- import_tasks: ara.yaml
  when: ansible_use_ara

- import_tasks: config.yaml

- import_tasks: ansible-bender.yaml
  when: ansible_install_ansible_bender
