---

- name: mitogen pip package
  pip:
    name: "{{ansible_mitogen_pip_package}}"
    version: "{{ansible_mitogen_version}}"

- name: get ansible_mitogen location
  shell: python3 -c "import os,ansible_mitogen; print(os.path.dirname(ansible_mitogen.__file__))"
  register: _ansible_mitogen_location
  changed_when: false
