---
galaxy_info:
  author: mkbrechtel
  description: Install and configure Podman container runtime with DNS support
  company: mkbrechtel
  license: Apache-2.0
  min_ansible_version: "2.14"
  platforms:
    - name: Debian
      versions:
        - bookworm
        - bullseye
    - name: Ubuntu
      versions:
        - jammy
        - focal
  galaxy_tags:
    - podman
    - containers
    - containerization
    - system

dependencies: []