---
galaxy_info:
  author: mkbrechtel
  description: Configure Ansible and install additional Ansible-related tools
  company: mkbrechtel
  license: Apache-2.0
  min_ansible_version: "2.14"
  platforms:
    - name: Debian
      versions:
        - bookworm
        - bullseye
    - name: Ubuntu
      versions:
        - jammy
        - focal
  galaxy_tags:
    - ansible
    - configuration
    - tools
    - system

dependencies: []