---

- name: required debian packages
  apt:
    pkg: python3-apt
    state: present

- name: apt sources.list
  template:
    src: sources.list.j2
    dest: /etc/apt/sources.list
  tags:
    - libreoffice-update

- name: update apt cache
  apt:
    update_cache: yes
  tags:
    - libreoffice-update
