---
galaxy_info:
  author: mkbrechtel
  description: System updates management for Debian/Ubuntu systems
  company: mkbrechtel
  license: Apache-2.0
  min_ansible_version: "2.14"
  platforms:
    - name: Debian
      versions:
        - bookworm
        - bullseye
    - name: Ubuntu
      versions:
        - jammy
        - focal
  galaxy_tags:
    - updates
    - system
    - maintenance
    - apt

dependencies: []